In [1]:
import VESIcal as v
# !pip install Thermobar
import Thermobar as pt

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
out=pt.import_excel('MI_compilation.xlsx', sheet_name="Galapagos_GEOROC")
my_input=out['my_input']
myOls=out['Ols']
myLiquids1=out['Liqs']

## Lets check the outputs have loaded right
display(myOls.head())
display(myLiquids1.head())

,SiO2_Ol,TiO2_Ol,Al2O3_Ol,FeOt_Ol,MnO_Ol,MgO_Ol,CaO_Ol,Na2O_Ol,K2O_Ol,Cr2O3_Ol,NiO_Ol,Sample_ID_Ol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Koleszar_2009_1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Koleszar_2009_2
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Koleszar_2009_3
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Koleszar_2009_4
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Koleszar_2009_5

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,Cr2O3_Liq,P2O5_Liq,H2O_Liq,Fe3Fet_Liq,NiO_Liq,CoO_Liq,CO2_Liq,Sample_ID_Liq
0,47.259000,1.519217,16.300067,11.295403,0.223233,7.269183,13.051900,2.433398,0.086267,0.0,0.079383,0.139195,0.0,0.0,0.0,0.000311,Koleszar_2009_1
1,50.372000,2.628000,18.009000,7.806976,0.166000,4.438000,13.577000,2.007000,0.006000,0.0,0.106000,0.874029,0.0,0.0,0.0,0.000491,Koleszar_2009_2
2,48.317400,1.535167,16.672367,11.441703,0.223433,7.692400,12.854400,2.649184,0.105867,0.0,0.098833,0.105384,0.0,0.0,0.0,0.000559,Koleszar_2009_3
3,47.386700,1.566867,16.264233,10.791070,0.220133,7.406700,13.094467,2.631095,0.090133,0.0,0.126033,0.108458,0.0,0.0,0.0,0.000678,Koleszar_2009_4
4,47.768933,1.621733,17.524467,10.255536,0.151100,5.446767,13.320600,3.005424,0.135667,0.0,0.120933,0.073393,0.0,0.0,0.0,0.000736,Koleszar_2009_5

In [4]:
T_HT87=pt.calculate_liq_only_temp(liq_comps=myLiquids1, equationT="T_Helz1987_MgO")
df_HT87=pt.convert_to_vesical(liq_comps=myLiquids1,
                              T1=T_HT87, unit='Kelvin', Fe3Fet_Liq=0.15)
df_HT87.head()

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Sample_ID,Temp,FeO,Fe2O3
0,47.259000,1.519217,16.300067,0.223233,7.269183,13.051900,2.433398,0.086267,0.0,0.079383,0.139195,0.0,0.0,0.000311,Koleszar_2009_1,1160.110585,9.601093,1.882567
1,50.372000,2.628000,18.009000,0.166000,4.438000,13.577000,2.007000,0.006000,0.0,0.106000,0.874029,0.0,0.0,0.000491,Koleszar_2009_2,1103.203800,6.635930,1.301163
2,48.317400,1.535167,16.672367,0.223433,7.692400,12.854400,2.649184,0.105867,0.0,0.098833,0.105384,0.0,0.0,0.000559,Koleszar_2009_3,1168.617240,9.725448,1.906950
3,47.386700,1.566867,16.264233,0.220133,7.406700,13.094467,2.631095,0.090133,0.0,0.126033,0.108458,0.0,0.0,0.000678,Koleszar_2009_4,1162.874670,9.172409,1.798511
4,47.768933,1.621733,17.524467,0.151100,5.446767,13.320600,3.005424,0.135667,0.0,0.120933,0.073393,0.0,0.0,0.000736,Koleszar_2009_5,1123.480010,8.717206,1.709256

In [5]:
VESIcal_out=v.BatchFile(filename=None, dataframe=df_HT87, label='Sample_ID')
VESIcal_out.data

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Temp,FeO,Fe2O3
Koleszar_2009_1,47.259000,1.519217,16.300067,0.223233,7.269183,13.051900,2.433398,0.086267,0.0,0.079383,0.139195,0.0,0.0,0.000311,1160.110585,9.601093,1.882567
Koleszar_2009_2,50.372000,2.628000,18.009000,0.166000,4.438000,13.577000,2.007000,0.006000,0.0,0.106000,0.874029,0.0,0.0,0.000491,1103.203800,6.635930,1.301163
Koleszar_2009_3,48.317400,1.535167,16.672367,0.223433,7.692400,12.854400,2.649184,0.105867,0.0,0.098833,0.105384,0.0,0.0,0.000559,1168.617240,9.725448,1.906950
Koleszar_2009_4,47.386700,1.566867,16.264233,0.220133,7.406700,13.094467,2.631095,0.090133,0.0,0.126033,0.108458,0.0,0.0,0.000678,1162.874670,9.172409,1.798511
Koleszar_2009_5,47.768933,1.621733,17.524467,0.151100,5.446767,13.320600,3.005424,0.135667,0.0,0.120933,0.073393,0.0,0.0,0.000736,1123.480010,8.717206,1.709256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Gleeson_2022_20,47.626000,2.373200,17.420100,0.148700,6.615600,13.702400,3.373100,0.707400,0.0,0.278700,0.616053,0.0,0.0,0.401686,1146.973560,6.766170,1.326700
Gleeson_2022_21,44.611317,2.249527,17.970881,0.170000,6.104757,13.068871,2.776900,1.170556,0.0,0.278200,0.692278,0.0,0.0,0.449901,1136.705615,7.092341,1.390655
Gleeson_2022_22,47.626000,2.373200,17.420100,0.148700,6.615600,13.702400,3.373100,0.707400,0.0,0.278700,0.753039,0.0,0.0,0.488552,1146.973560,6.766170,1.326700
Gleeson_2022_23,45.140500,2.054600,15.392300,0.149100,6.928100,12.367800,3.540500,1.003500,0.0,0.249700,0.544165,0.0,0.0,0.871109,1153.254810,8.431490,1.653233
Gleeson_2022_24,46.468400,2.059500,15.621200,0.202300,7.073000,12.432600,3.468800,0.937800,0.0,0.252600,0.579897,0.0,0.0,0.891235,1156.167300,8.265060,1.620600

In [6]:
Sat_P_MagmaSat=VESIcal_out.calculate_saturation_pressure(temperature="Temp")

[====================] 100%  Working on sample Gleeson_2022_24

In [7]:
Sat_P_MagmaSat.head()

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,...,FeO,Fe2O3,Temp,SaturationP_bars_VESIcal,XH2O_fl_VESIcal,XCO2_fl_VESIcal,FluidMass_grams_VESIcal,FluidSystem_wt_VESIcal,Model,Warnings
Koleszar_2009_1,47.259000,1.519217,16.300067,0.223233,7.269183,13.051900,2.433398,0.086267,0.0,0.079383,...,9.601093,1.882567,1160.110585,0,0.000000,0.000000,0.000000,0.000000,MagmaSat,
Koleszar_2009_2,50.372000,2.628000,18.009000,0.166000,4.438000,13.577000,2.007000,0.006000,0.0,0.106000,...,6.635930,1.301163,1103.203800,120,0.973300,0.026700,0.005330,0.005330,MagmaSat,
Koleszar_2009_3,48.317400,1.535167,16.672367,0.223433,7.692400,12.854400,2.649184,0.105867,0.0,0.098833,...,9.725448,1.906950,1168.617240,10,0.228116,0.771884,0.000149,0.000149,MagmaSat,
Koleszar_2009_4,47.386700,1.566867,16.264233,0.220133,7.406700,13.094467,2.631095,0.090133,0.0,0.126033,...,9.172409,1.798511,1162.874670,10,0.238688,0.761312,0.000296,0.000296,MagmaSat,
Koleszar_2009_5,47.768933,1.621733,17.524467,0.151100,5.446767,13.320600,3.005424,0.135667,0.0,0.120933,...,8.717206,1.709256,1123.480010,10,0.104595,0.895405,0.000316,0.000316,MagmaSat,

In [8]:
Sat_P_MagmaSat.to_excel(excel_writer='XH2O_Galapagos_Georoc.xlsx')