In [1]:
import VESIcal as v
# !pip install Thermobar
import Thermobar as pt

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [4]:
# Load in melt inclusion data
out=pt.import_excel('MI_compilation_XH2O.xlsx', sheet_name='Intraplate compilation')
my_input=out['my_input']
myOls=out['Ols']
myLiquids1=out['Liqs']

## Lets check the outputs have loaded right
display(myOls.head())
display(myLiquids1.head())

,SiO2_Ol,TiO2_Ol,Al2O3_Ol,FeOt_Ol,MnO_Ol,MgO_Ol,CaO_Ol,Na2O_Ol,K2O_Ol,Cr2O3_Ol,NiO_Ol,Sample_ID_Ol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,harris83_1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,schipper_2011_1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,schipper_2011_2
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,schipper_2011_3
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,schipper_2011_4

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,Cr2O3_Liq,P2O5_Liq,H2O_Liq,Fe3Fet_Liq,NiO_Liq,CoO_Liq,CO2_Liq,Sample_ID_Liq
0,51.8,2.40,14.0,8.40,0.0,9.40,11.4,2.12,0.45,0.0,0.00,0.46,0.0,0.0,0.0,0.3100,harris83_1
1,53.3,2.82,14.2,7.86,0.0,3.57,13.9,2.36,0.63,0.0,0.11,0.73,0.0,0.0,0.0,0.0192,schipper_2011_1
2,49.5,2.84,13.3,9.12,0.0,4.59,14.1,2.38,0.44,0.0,0.26,0.75,0.0,0.0,0.0,0.0481,schipper_2011_2
3,51.9,2.48,13.8,9.08,0.0,4.92,14.2,1.67,0.61,0.0,0.06,0.59,0.0,0.0,0.0,0.0140,schipper_2011_3
4,50.2,2.82,13.6,10.74,0.0,5.40,11.4,2.42,0.46,0.0,0.12,0.77,0.0,0.0,0.0,0.0187,schipper_2011_4

In [5]:
T_HT87=pt.calculate_liq_only_temp(liq_comps=myLiquids1, equationT="T_Helz1987_CaO")
df_HT87=pt.convert_to_vesical(liq_comps=myLiquids1,
                              T1=T_HT87, unit='Kelvin', Fe3Fet_Liq=0.15)
df_HT87.head()

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Sample_ID,Temp,FeO,Fe2O3
0,51.8,2.40,14.0,0.0,9.40,11.4,2.12,0.45,0.0,0.00,0.46,0.0,0.0,0.3100,harris83_1,1157.24,7.140,1.400000
1,53.3,2.82,14.2,0.0,3.57,13.9,2.36,0.63,0.0,0.11,0.73,0.0,0.0,0.0192,schipper_2011_1,1198.74,6.681,1.310000
2,49.5,2.84,13.3,0.0,4.59,14.1,2.38,0.44,0.0,0.26,0.75,0.0,0.0,0.0481,schipper_2011_2,1202.06,7.752,1.520000
3,51.9,2.48,13.8,0.0,4.92,14.2,1.67,0.61,0.0,0.06,0.59,0.0,0.0,0.0140,schipper_2011_3,1203.72,7.718,1.513333
4,50.2,2.82,13.6,0.0,5.40,11.4,2.42,0.46,0.0,0.12,0.77,0.0,0.0,0.0187,schipper_2011_4,1157.24,9.129,1.790000

In [6]:
VESIcal_out=v.BatchFile(filename=None, dataframe=df_HT87, label='Sample_ID')
VESIcal_out.data

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Temp,FeO,Fe2O3
harris83_1,51.800,2.400,14.000,0.000,9.400,11.400,2.120,0.450,0.0,0.000,0.460000,0.0,0.0,0.310000,1157.2400,7.14000,1.400000
schipper_2011_1,53.300,2.820,14.200,0.000,3.570,13.900,2.360,0.630,0.0,0.110,0.730000,0.0,0.0,0.019200,1198.7400,6.68100,1.310000
schipper_2011_2,49.500,2.840,13.300,0.000,4.590,14.100,2.380,0.440,0.0,0.260,0.750000,0.0,0.0,0.048100,1202.0600,7.75200,1.520000
schipper_2011_3,51.900,2.480,13.800,0.000,4.920,14.200,1.670,0.610,0.0,0.060,0.590000,0.0,0.0,0.014000,1203.7200,7.71800,1.513333
schipper_2011_4,50.200,2.820,13.600,0.000,5.400,11.400,2.420,0.460,0.0,0.120,0.770000,0.0,0.0,0.018700,1157.2400,9.12900,1.790000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wieser_2021_145,49.272,1.896,11.320,0.132,13.414,9.501,2.216,0.313,0.0,0.209,0.290317,0.0,0.0,0.098694,1125.7166,9.63305,1.888833
Wieser_2021_146,49.022,2.026,11.316,0.183,13.473,9.840,1.933,0.344,0.0,0.179,0.237103,0.0,0.0,0.037876,1131.3440,9.63305,1.888833
Wieser_2021_147,49.755,1.798,11.177,0.163,13.478,9.264,2.181,0.283,0.0,0.200,0.254953,0.0,0.0,0.075558,1121.7824,9.63730,1.889666
Wieser_2021_148,49.676,1.815,10.928,0.151,13.612,9.435,2.131,0.334,0.0,0.229,0.238325,0.0,0.0,0.039774,1124.6210,9.63560,1.889333
Wieser_2021_149,49.279,2.023,10.983,0.202,13.734,9.581,1.991,0.337,0.0,0.192,0.222556,0.0,0.0,0.115246,1127.0446,9.63475,1.889166

In [7]:
df= VESIcal_out.get_data()
chunk_size = 20
subframes = [v.BatchFile(filename=None,dataframe=df.iloc[i:i+chunk_size],label=None) for i in range(0, len(df), chunk_size)]

In [8]:
# import multiprocessing

# def process_data(index, data):
#     Sat_P_MagmaSat = data.calculate_saturation_pressure(temperature="Temp")
#     filename = f"XH2O_OIB_comp_Devitre2023_{index}.xlsx"
#     Sat_P_MagmaSat.to_excel(excel_writer=filename)

# if __name__ == "__main__":
#     # Create a pool of worker processes
#     with multiprocessing.Pool() as pool:
#         # Use map to distribute the workload across the processes
#         pool.starmap(process_data, enumerate(subframes))

In [9]:
for index, data in enumerate(subframes):
    if index in [29]:
        Sat_P_MagmaSat = data.calculate_saturation_pressure(temperature="Temp")
        filename = f"XH2O_OIB_comp_Devitre2023_{index}.xlsx"
        Sat_P_MagmaSat.to_excel(excel_writer=filename)

[====================] 100%  Working on sample Wieser_2021_85

In [10]:
pd.read_excel('XH2O_OIB_comp_Devitre2023_29.xlsx')

,Unnamed: 0,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,...,FeO,Fe2O3,Temp,SaturationP_bars_VESIcal,XH2O_fl_VESIcal,XCO2_fl_VESIcal,FluidMass_grams_VESIcal,FluidSystem_wt_VESIcal,Model,Warnings
0,Wieser_2021_66,50.852,2.233,13.333,0.207,7.618,10.837,2.556,0.401,0,...,9.63390,1.889000,1147.8942,150,0.035905,0.964095,0.000300,0.000300,MagmaSat,NaN
1,Wieser_2021_67,51.241,3.417,12.558,0.208,7.665,9.749,2.600,0.564,0,...,9.63645,1.889500,1129.8334,380,0.030535,0.969465,0.000338,0.000338,MagmaSat,NaN
2,Wieser_2021_68,51.013,2.422,12.885,0.214,7.666,11.233,2.201,0.404,0,...,9.63305,1.888833,1154.4678,20,0.505647,0.494353,0.000612,0.000612,MagmaSat,NaN
3,Wieser_2021_69,51.446,2.536,13.028,0.152,7.682,10.541,2.296,0.503,0,...,9.63645,1.889500,1142.9806,510,0.003934,0.996066,0.000270,0.000270,MagmaSat,NaN
4,Wieser_2021_70,51.232,2.519,13.068,0.158,7.683,10.816,2.248,0.434,0,...,9.63730,1.889666,1147.5456,380,0.004906,0.995094,0.000441,0.000441,MagmaSat,NaN
5,Wieser_2021_71,51.167,2.376,12.879,0.188,7.728,11.084,2.176,0.405,0,...,9.66790,1.895666,1151.9944,300,0.033716,0.966284,0.000245,0.000245,MagmaSat,NaN
6,Wieser_2021_72,50.101,2.966,13.543,0.222,7.754,10.320,2.646,0.495,0,...,9.63985,1.890166,1139.3120,2230,0.009598,0.990402,0.000553,0.000553,MagmaSat,NaN
7,Wieser_2021_73,51.033,2.194,13.085,0.208,7.755,10.975,2.398,0.351,0,...,9.64240,1.890666,1150.1850,1090,0.012335,0.987665,0.000272,0.000272,MagmaSat,NaN
8,Wieser_2021_74,51.708,2.111,12.876,0.226,8.140,9.612,2.837,0.368,0,...,9.63135,1.888500,1127.5592,800,0.027464,0.972536,0.000296,0.000296,MagmaSat,NaN
9,Wieser_2021_75,50.838,2.470,12.907,0.129,8.431,10.193,2.633,0.392,0,...,9.63730,1.889666,1137.2038,200,0.055254,0.944746,0.000593,0.000593,MagmaSat,NaN
10,Wieser_2021_76,50.864,2.199,13.064,0.224,8.680,10.091,2.455,0.346,0,...,9.63645,1.889500,1135.5106,970,0.023365,0.976635,0.000638,0.000638,MagmaSat,NaN
11,Wieser_2021_77,49.329,2.218,13.395,0.184,8.866,11.143,2.232,0.491,0,...,9.63220,1.888666,1152.9738,260,0.047457,0.952543,0.000594,0.000594,MagmaSat,NaN
12,Wieser_2021_78,50.168,2.372,12.643,0.256,9.004,11.014,2.103,0.459,0,...,9.63220,1.888666,1150.8324,160,0.076255,0.923745,0.000463,0.000463,MagmaSat,NaN
13,Wieser_2021_79,49.754,2.681,13.085,0.249,9.184,10.218,2.357,0.517,0,...,9.63220,1.888666,1137.6188,340,0.036860,0.963140,0.000600,0.000600,MagmaSat,NaN
14,Wieser_2021_80,50.542,2.042,12.855,0.113,9.200,10.314,2.457,0.441,0,...,9.63135,1.888500,1139.2124,640,0.030576,0.969424,0.000129,0.000129,MagmaSat,NaN
15,Wieser_2021_81,49.770,2.394,12.900,0.142,9.328,10.702,2.469,0.349,0,...,9.63560,1.889333,1145.6532,370,0.034837,0.965163,0.000055,0.000055,MagmaSat,NaN
16,Wieser_2021_82,50.557,2.163,12.827,0.162,9.527,10.109,2.321,0.438,0,...,9.63730,1.889666,1135.8094,60,0.144826,0.855174,0.000093,0.000093,MagmaSat,NaN
17,Wieser_2021_83,49.585,2.282,12.839,0.144,9.906,10.463,2.348,0.477,0,...,9.64240,1.890666,1141.6858,390,0.028947,0.971053,0.000672,0.000672,MagmaSat,NaN
18,Wieser_2021_84,50.299,2.200,12.245,0.141,9.967,10.351,2.403,0.388,0,...,9.64325,1.890833,1139.8266,1080,0.018642,0.981358,0.000266,0.000266,MagmaSat,NaN
19,Wieser_2021_85,49.580,2.651,12.393,0.180,9.971,10.484,2.282,0.441,0,...,9.63305,1.888833,1142.0344,470,0.031760,0.968240,0.000172,0.000172,MagmaSat,NaN

In [11]:
import os
combined_data = pd.DataFrame()

for index in range(len(subframes)):
    filename = f"XH2O_OIB_comp_Devitre2023_{index}.xlsx"
    if os.path.exists(filename):
        df = pd.read_excel(filename)
        combined_data = pd.concat([combined_data, df])

combined_filename = "XH2O_OIB_comp_Devitre2023_combined.xlsx"
combined_data.to_excel(combined_filename, index=False)