In [1]:
import VESIcal as v
# !pip install Thermobar
import Thermobar as pt

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
out=pt.import_excel('MI_compilation_XH2O.xlsx', sheet_name="Moore_2015_bubbles")
my_input=out['my_input']
myOls=out['Ols']
myLiquids1=out['Liqs']

## Lets check the outputs have loaded right
display(myOls.head())
display(myLiquids1.head())

,SiO2_Ol,TiO2_Ol,Al2O3_Ol,FeOt_Ol,MnO_Ol,MgO_Ol,CaO_Ol,Na2O_Ol,K2O_Ol,Cr2O3_Ol,NiO_Ol,Sample_ID_Ol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,Cr2O3_Liq,P2O5_Liq,H2O_Liq,Fe3Fet_Liq,NiO_Liq,CoO_Liq,CO2_Liq,Sample_ID_Liq
0,51.805898,0.918118,16.830570,9.498479,0.209010,4.037046,7.337308,3.829945,0.812181,0.0,0.0,4.022052,0.0,0.0,0.0,0.018807,Moore_2015_1
1,50.064416,0.685123,16.860688,10.772670,0.160814,4.739719,8.061615,3.106843,0.536680,0.0,0.0,4.311120,0.0,0.0,0.0,0.049464,Moore_2015_2
2,49.943526,0.746065,17.690493,9.563306,0.220774,4.269889,9.040327,2.982356,0.561452,0.0,0.0,4.297534,0.0,0.0,0.0,0.051225,Moore_2015_3
3,48.767878,1.079099,19.070395,8.163041,0.137374,3.995224,9.556514,3.231612,0.620553,0.0,0.0,4.679944,0.0,0.0,0.0,0.069067,Moore_2015_4
4,52.826840,1.091744,16.051405,9.139767,0.202493,3.962944,7.911561,3.395581,0.784183,0.0,0.0,4.035278,0.0,0.0,0.0,0.026936,Moore_2015_5

In [4]:
T_HT87=pt.calculate_liq_only_temp(liq_comps=myLiquids1, equationT="T_Helz1987_MgO")
df_HT87=pt.convert_to_vesical(liq_comps=myLiquids1,
                              T1=T_HT87, unit='Kelvin', Fe3Fet_Liq=0.15)
df_HT87.head()

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Sample_ID,Temp,FeO,Fe2O3
0,51.805898,0.918118,16.830570,0.209010,4.037046,7.337308,3.829945,0.812181,0.0,0.0,4.022052,0.0,0.0,0.018807,Moore_2015_1,1095.144631,8.073708,1.583080
1,50.064416,0.685123,16.860688,0.160814,4.739719,8.061615,3.106843,0.536680,0.0,0.0,4.311120,0.0,0.0,0.049464,Moore_2015_2,1109.268360,9.156770,1.795445
2,49.943526,0.746065,17.690493,0.220774,4.269889,9.040327,2.982356,0.561452,0.0,0.0,4.297534,0.0,0.0,0.051225,Moore_2015_3,1099.824775,8.128810,1.593884
3,48.767878,1.079099,19.070395,0.137374,3.995224,9.556514,3.231612,0.620553,0.0,0.0,4.679944,0.0,0.0,0.069067,Moore_2015_4,1094.303996,6.938585,1.360507
4,52.826840,1.091744,16.051405,0.202493,3.962944,7.911561,3.395581,0.784183,0.0,0.0,4.035278,0.0,0.0,0.026936,Moore_2015_5,1093.655180,7.768802,1.523294

In [5]:
VESIcal_out=v.BatchFile(filename=None, dataframe=df_HT87, label='Sample_ID')
VESIcal_out.data

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Temp,FeO,Fe2O3
Moore_2015_1,51.805898,0.918118,16.830570,0.209010,4.037046,7.337308,3.829945,0.812181,0.000000,0.0,4.022052,0.0,0.0,0.018807,1095.144631,8.073708,1.583080
Moore_2015_2,50.064416,0.685123,16.860688,0.160814,4.739719,8.061615,3.106843,0.536680,0.000000,0.0,4.311120,0.0,0.0,0.049464,1109.268360,9.156770,1.795445
Moore_2015_3,49.943526,0.746065,17.690493,0.220774,4.269889,9.040327,2.982356,0.561452,0.000000,0.0,4.297534,0.0,0.0,0.051225,1099.824775,8.128810,1.593884
Moore_2015_4,48.767878,1.079099,19.070395,0.137374,3.995224,9.556514,3.231612,0.620553,0.000000,0.0,4.679944,0.0,0.0,0.069067,1094.303996,6.938585,1.360507
Moore_2015_5,52.826840,1.091744,16.051405,0.202493,3.962944,7.911561,3.395581,0.784183,0.000000,0.0,4.035278,0.0,0.0,0.026936,1093.655180,7.768802,1.523294
Moore_2015_6,50.159947,0.722590,17.613846,0.189704,4.572908,8.654874,2.782639,0.577691,0.000000,0.0,4.129068,0.0,0.0,0.049002,1105.915448,8.425313,1.652022
Moore_2015_7,50.579815,0.649381,18.160620,0.082492,5.777289,10.249101,2.492013,0.321334,0.045083,0.0,3.894639,0.0,0.0,0.009901,1130.123510,6.354701,1.246020
Moore_2015_8,50.845113,0.674043,18.848237,0.067212,5.363538,10.133688,2.826756,0.372548,0.011522,0.0,3.785026,0.0,0.0,0.019102,1121.807117,5.777504,1.132844
Moore_2015_9,49.648525,0.652374,18.017989,0.199550,5.842583,10.532959,2.303455,0.285893,0.023984,0.0,3.873081,0.0,0.0,0.011332,1131.435919,7.080685,1.388370
Moore_2015_10,50.811116,0.737034,17.798352,0.121077,6.172056,9.613148,2.435959,0.458364,0.049007,0.0,3.693060,0.0,0.0,0.017937,1138.058322,6.632979,1.300584
Moore_2015_11,49.193160,0.627439,18.687155,0.107287,6.038744,10.586961,2.450366,0.298872,0.036401,0.0,4.006786,0.0,0.0,0.018162,1135.378763,6.525910,1.279590
Moore_2015_12,49.605501,0.679700,18.123073,0.125080,6.517752,10.712306,2.283443,0.318034,0.053329,0.0,2.868401,0.0,0.0,0.005807,1145.006809,7.176054,1.407069
Moore_2015_13,49.769740,0.852330,17.572953,0.173534,6.305707,10.124414,2.273199,0.356655,0.024928,0.0,3.855853,0.0,0.0,0.050073,1140.744720,7.072183,1.386702
Moore_2015_14,51.712070,0.550709,17.687821,0.178142,5.834644,9.344816,2.473881,0.415666,0.021071,0.0,4.085495,0.0,0.0,0.017886,1131.276342,6.348924,1.244887
Moore_2015_15,47.147865,0.608968,18.749360,0.105783,6.539499,10.106586,2.739881,0.359282,0.000000,0.0,4.455424,0.0,0.0,0.019839,1145.443936,7.505433,1.471653
Moore_2015_16,49.725268,0.639634,17.778164,0.080675,6.457802,10.107363,2.174370,0.286202,0.050902,0.0,3.783642,0.0,0.0,0.004787,1143.801822,7.342717,1.439748
Moore_2015_17,49.973292,0.629432,18.524665,0.137958,5.697465,10.137023,2.591499,0.310405,0.012455,0.0,3.992446,0.0,0.0,0.020099,1128.519046,6.544055,1.283148
Moore_2015_18,55.683885,1.040938,14.974545,0.190499,4.683737,7.124256,2.886636,0.921391,0.010691,0.0,2.565456,0.0,0.0,0.004881,1108.143107,8.100210,1.588276
Moore_2015_19,49.655724,0.626254,18.341114,0.188354,6.320862,10.276302,1.808010,0.332727,0.014342,0.0,4.164800,0.0,0.0,0.022270,1141.049335,6.766573,1.326779
Moore_2015_20,50.438891,0.613460,17.373385,0.192665,6.408742,10.205486,2.125065,0.270306,0.010544,0.0,3.934497,0.0,0.0,0.019886,1142.815720,6.900932,1.353124
Moore_2015_21,53.464549,0.700853,14.861388,0.101784,7.457352,7.533932,2.671580,0.473052,0.004847,0.0,2.919271,0.0,0.0,0.005534,1163.892769,8.101925,1.588613

In [6]:
df= VESIcal_out.get_data()
chunk_size = 20
subframes = [v.BatchFile(filename=None,dataframe=df.iloc[i:i+chunk_size],label=None) for i in range(0, len(df), chunk_size)]

In [10]:
for index, data in enumerate(subframes):
    if index>=0:
        Sat_P_MagmaSat = data.calculate_saturation_pressure(temperature="Temp")
        filename = f"XH2O_Moore2015_{index}.xlsx"
        Sat_P_MagmaSat.to_excel(excel_writer=filename)

[====================] 100%  Working on sample Moore_2015_20
[====================] 100%  Working on sample Moore_2015_21

In [8]:
import os
combined_data = pd.DataFrame()

for index in range(len(subframes)):
    filename = f"XH2O_Moore2015_{index}.xlsx"
    if os.path.exists(filename):
        df = pd.read_excel(filename)
        combined_data = pd.concat([combined_data, df])

combined_filename = "XH2O_Moore2015_combined.xlsx"
combined_data.to_excel(combined_filename, index=False)