In [1]:
import VESIcal as v
# !pip install Thermobar
import Thermobar as pt

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
out=pt.import_excel('MI_compilation_XH2O.xlsx', sheet_name="Miller_Midfell_2019")
my_input=out['my_input']
myOls=out['Ols']
myLiquids1=out['Liqs']

## Lets check the outputs have loaded right
display(myOls.head())
display(myLiquids1.head())

,SiO2_Ol,TiO2_Ol,Al2O3_Ol,FeOt_Ol,MnO_Ol,MgO_Ol,CaO_Ol,Na2O_Ol,K2O_Ol,Cr2O3_Ol,NiO_Ol,Sample_ID_Ol
0,39.7457,0.0173,0.0556,12.7562,0.2190,46.2124,0.3426,0.0,0.0,0.0387,0.2229,Miller_2019_Midfell_1
1,39.6404,0.0025,0.0665,12.4598,0.2079,46.3979,0.3657,0.0,0.0,0.0313,0.2319,Miller_2019_Midfell_2
2,39.7642,0.0056,0.0704,12.3638,0.1861,46.4012,0.3448,0.0,0.0,0.0350,0.2481,Miller_2019_Midfell_3
3,39.8190,0.0069,0.0522,12.8008,0.2022,45.9652,0.3736,0.0,0.0,0.0340,0.2140,Miller_2019_Midfell_4
4,39.9073,0.0040,0.0839,10.9986,0.1683,47.4855,0.3679,0.0,0.0,0.0609,0.3078,Miller_2019_Midfell_5

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,Cr2O3_Liq,P2O5_Liq,H2O_Liq,Fe3Fet_Liq,NiO_Liq,CoO_Liq,CO2_Liq,Sample_ID_Liq
0,47.124,0.860,16.041,9.692,0.158,9.671,14.634,1.608,0.026,0.075,0.014,0.063,0.0,0.0,0.0,0.076131,Miller_2019_Midfell_1
1,47.454,0.891,16.069,9.190,0.185,9.465,15.006,1.528,0.030,0.063,0.029,0.067,0.0,0.0,0.0,0.042131,Miller_2019_Midfell_2
2,47.506,0.898,16.137,9.157,0.162,9.512,14.851,1.571,0.017,0.075,0.025,0.072,0.0,0.0,0.0,0.062943,Miller_2019_Midfell_3
3,47.584,0.884,15.959,9.417,0.188,9.382,14.765,1.616,0.029,0.051,0.032,0.066,0.0,0.0,0.0,0.013624,Miller_2019_Midfell_4
4,47.610,0.869,16.622,8.252,0.149,9.758,14.852,1.725,0.017,0.044,0.000,0.064,0.0,0.0,0.0,0.075874,Miller_2019_Midfell_5

In [3]:
T_HT87=pt.calculate_liq_only_temp(liq_comps=myLiquids1, equationT="T_Helz1987_MgO")
df_HT87=pt.convert_to_vesical(liq_comps=myLiquids1,
                              T1=T_HT87, unit='Kelvin', Fe3Fet_Liq=0.15)
df_HT87.head()

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Sample_ID,Temp,FeO,Fe2O3
0,47.124,0.860,16.041,0.158,9.671,14.634,1.608,0.026,0.075,0.014,0.063,0.0,0.0,0.076131,Miller_2019_Midfell_1,1208.3871,8.23820,1.615333
1,47.454,0.891,16.069,0.185,9.465,15.006,1.528,0.030,0.063,0.029,0.067,0.0,0.0,0.042131,Miller_2019_Midfell_2,1204.2465,7.81150,1.531667
2,47.506,0.898,16.137,0.162,9.512,14.851,1.571,0.017,0.075,0.025,0.072,0.0,0.0,0.062943,Miller_2019_Midfell_3,1205.1912,7.78345,1.526167
3,47.584,0.884,15.959,0.188,9.382,14.765,1.616,0.029,0.051,0.032,0.066,0.0,0.0,0.013624,Miller_2019_Midfell_4,1202.5782,8.00445,1.569500
4,47.610,0.869,16.622,0.149,9.758,14.852,1.725,0.017,0.044,0.000,0.064,0.0,0.0,0.075874,Miller_2019_Midfell_5,1210.1358,7.01420,1.375333

In [4]:
VESIcal_out=v.BatchFile(filename=None, dataframe=df_HT87, label='Sample_ID')
VESIcal_out.data

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Temp,FeO,Fe2O3
Miller_2019_Midfell_1-duplicate-0.0,47.124000,0.860000,16.041000,0.158000,9.671000,14.634000,1.608000,0.026000,0.075000,0.014000,0.063,0.0,0.0,0.076131,1208.387100,8.23820,1.615333
Miller_2019_Midfell_2-duplicate-0.0,47.454000,0.891000,16.069000,0.185000,9.465000,15.006000,1.528000,0.030000,0.063000,0.029000,0.067,0.0,0.0,0.042131,1204.246500,7.81150,1.531667
Miller_2019_Midfell_3-duplicate-0.0,47.506000,0.898000,16.137000,0.162000,9.512000,14.851000,1.571000,0.017000,0.075000,0.025000,0.072,0.0,0.0,0.062943,1205.191200,7.78345,1.526167
Miller_2019_Midfell_4-duplicate-0.0,47.584000,0.884000,15.959000,0.188000,9.382000,14.765000,1.616000,0.029000,0.051000,0.032000,0.066,0.0,0.0,0.013624,1202.578200,8.00445,1.569500
Miller_2019_Midfell_5-duplicate-0.0,47.610000,0.869000,16.622000,0.149000,9.758000,14.852000,1.725000,0.017000,0.044000,0.000000,0.064,0.0,0.0,0.075874,1210.135800,7.01420,1.375333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Miller_2019_Midfell_74-duplicate-0.0,50.291000,0.983000,17.693000,0.078000,6.843000,17.066000,1.657000,0.047000,0.019000,0.038000,0.046,0.0,0.0,0.034886,1151.544300,4.45400,0.873333
Miller_2019_Midfell_75-duplicate-0.0,50.303000,1.458000,17.000000,0.153000,6.911000,15.773000,1.899000,0.156000,0.063000,0.138000,0.066,0.0,0.0,0.047883,1152.911100,5.17650,1.015000
Miller_2019_Midfell_76-duplicate-0.0,50.499000,0.709000,16.173000,0.186000,8.871000,14.072000,1.744000,0.024000,0.114000,0.038000,0.062,0.0,0.0,0.009074,1192.307100,6.37500,1.250000
Miller_2019_Midfell_77-duplicate-0.0,50.507000,2.560000,16.876000,0.162000,6.496000,13.188000,2.624000,0.546000,0.035000,0.440000,0.076,0.0,0.0,0.024763,1144.569600,5.51905,1.082167
nan-duplicate-nan,49.001935,0.950195,16.102675,0.168156,9.082312,14.854182,1.720896,0.070909,0.074455,0.070592,0.000,0.0,0.0,0.000000,1196.554465,6.65369,1.304645

In [5]:
Sat_P_MagmaSat=VESIcal_out.calculate_saturation_pressure(temperature="Temp")

[====================] 100%  Working on sample nan-duplicate-nan

In [6]:
Sat_P_MagmaSat.head()

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,...,FeO,Fe2O3,Temp,SaturationP_bars_VESIcal,XH2O_fl_VESIcal,XCO2_fl_VESIcal,FluidMass_grams_VESIcal,FluidSystem_wt_VESIcal,Model,Warnings
Miller_2019_Midfell_1-duplicate-0.0,47.124,0.860,16.041,0.158,9.671,14.634,1.608,0.026,0.075,0.014,...,8.23820,1.615333,1208.3871,1500,0.000739,0.999261,0.000449,0.000449,MagmaSat,
Miller_2019_Midfell_2-duplicate-0.0,47.454,0.891,16.069,0.185,9.465,15.006,1.528,0.030,0.063,0.029,...,7.81150,1.531667,1204.2465,850,0.001383,0.998617,0.000268,0.000268,MagmaSat,
Miller_2019_Midfell_3-duplicate-0.0,47.506,0.898,16.137,0.162,9.512,14.851,1.571,0.017,0.075,0.025,...,7.78345,1.526167,1205.1912,1270,0.001107,0.998893,0.000376,0.000376,MagmaSat,
Miller_2019_Midfell_4-duplicate-0.0,47.584,0.884,15.959,0.188,9.382,14.765,1.616,0.029,0.051,0.032,...,8.00445,1.569500,1202.5782,260,0.003859,0.996141,0.000504,0.000504,MagmaSat,
Miller_2019_Midfell_5-duplicate-0.0,47.610,0.869,16.622,0.149,9.758,14.852,1.725,0.017,0.044,0.000,...,7.01420,1.375333,1210.1358,1550,0.000714,0.999286,0.000178,0.000178,MagmaSat,

In [7]:
Sat_P_MagmaSat.to_excel(excel_writer='XH2O_Miller_Midfell.xlsx')