In [1]:
import VESIcal as v

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
# Load in melt inclusion data
myfile= v.BatchFile('MI_compilation.xlsx', sheet_name='Miller_Midfell_2019',  input_type='wtpercent',label='Mount')

In [4]:
myfile.get_data()

,CO2,H2O,SiO2,TiO2,Al2O3,Cr2O3,FeO,MgO,CaO,MnO,...,SiO2_ol,TiO2_ol,Al2O3_ol,Cr2O3_ol,NiO_ol,FeO_ol,MgO_ol,CaO_ol,MnO_ol,PEC_corr
mt9,0.069295,0.040,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,40.7697,0.0109,0.0973,0.0882,0.3008,11.4142,47.2497,0.3912,0.1977,na
mt9-duplicate-1,0.039649,0.041,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,40.8562,0.0075,0.0709,0.042,0.2558,11.7896,47.2965,0.3647,0.1986,na
mt9-duplicate-2,0.085285,0.041,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,40.5331,0.0124,0.0688,0.0496,0.2234,12.707,46.2542,0.369,0.1912,na
mt9-duplicate-3,0.107928,0.041,49.021,0.774,15.930,0.031,7.433,9.692,15.385,0.131,...,40.8753,0.0026,0.0739,0.0824,0.3072,10.2894,48.0255,0.3939,0.1502,1.61
mt9-duplicate-4,0.016535,0.043,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,41.0556,0.0086,0.102,0.1033,0.3792,9.7844,48.7394,0.3644,0.1643,na
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mid01a-duplicate-3,0.058113,0.095,48.403,0.826,16.565,0.043,7.356,9.453,15.494,0.203,...,40.484,0.0079,0.1065,0.0975,0.3567,10.4046,48.2192,0.3621,0.1716,1.73
mt10-duplicate-6,0.073727,0.097,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,40.2135,0.0086,0.0984,0.0737,0.2591,12.4332,46.3625,0.3518,0.1733,na
mid01a-duplicate-4,0.018037,0.101,50.148,0.763,15.551,0.238,6.982,9.211,15.000,0.182,...,39.7747,0.0069,0.0998,0.0906,0.3114,10.3418,48.2646,0.3567,0.1529,1.3
mid01a-duplicate-5,0.015008,0.105,50.136,0.780,15.643,0.077,6.953,9.151,15.162,0.179,...,39.7747,0.0069,0.0998,0.0906,0.3114,10.3418,48.2646,0.3567,0.1529,1.46
mid01a-duplicate-6,0.015385,0.112,50.095,0.782,15.645,0.043,7.027,9.215,15.073,0.152,...,39.7747,0.0069,0.0998,0.0906,0.3114,10.3418,48.2646,0.3567,0.1529,1.7

In [ ]:
Sat_P_MagmaSat=myfile.calculate_saturation_pressure(temperature=1200)

[===========         ] 58%  Working on sample mt4-duplicate-4