In [1]:
import VESIcal as v
# !pip install Thermobar
import Thermobar as pt

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [9]:
out=pt.import_excel('MI_compilation_XH2O.xlsx', sheet_name="Moore_2018_kluychev")
my_input=out['my_input']
myOls=out['Ols']
myLiquids1=out['Liqs']

## Lets check the outputs have loaded right
display(myOls.head())
display(myLiquids1.head())

,SiO2_Ol,TiO2_Ol,Al2O3_Ol,FeOt_Ol,MnO_Ol,MgO_Ol,CaO_Ol,Na2O_Ol,K2O_Ol,Cr2O3_Ol,NiO_Ol,Sample_ID_Ol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,Cr2O3_Liq,P2O5_Liq,H2O_Liq,Fe3Fet_Liq,NiO_Liq,CoO_Liq,CO2_Liq,Sample_ID_Liq
0,48.347,0.859,19.172,9.175081,0.128,8.064,9.060,2.748,0.615,0,0.163,1.573,0.0,0.0,0.0,0.1528,Moore_2018_Klyuchevskoy_1
1,49.874,0.916,16.445,9.232479,0.146,8.179,9.834,2.738,0.635,0,0.178,1.719,0.0,0.0,0.0,0.0481,Moore_2018_Klyuchevskoy_2
2,49.172,0.851,15.432,9.186880,0.157,8.768,10.814,2.544,0.537,0,0.152,2.284,0.0,0.0,0.0,0.0590,Moore_2018_Klyuchevskoy_3
3,49.562,0.935,16.467,9.213878,0.116,8.610,10.049,2.822,0.632,0,0.174,1.310,0.0,0.0,0.0,0.0337,Moore_2018_Klyuchevskoy_4
4,48.517,0.831,15.055,9.174880,0.152,9.973,10.987,2.475,0.451,0,0.186,2.095,0.0,0.0,0.0,0.0664,Moore_2018_Klyuchevskoy_5

In [10]:
T_HT87=pt.calculate_liq_only_temp(liq_comps=myLiquids1, equationT="T_Helz1987_MgO")
df_HT87=pt.convert_to_vesical(liq_comps=myLiquids1,
                              T1=T_HT87, unit='Kelvin', Fe3Fet_Liq=0.15)
df_HT87.head()

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Sample_ID,Temp,FeO,Fe2O3
0,48.347,0.859,19.172,0.128,8.064,9.060,2.748,0.615,0,0.163,1.573,0.0,0.0,0.1528,Moore_2018_Klyuchevskoy_1,1176.0864,7.798819,1.529180
1,49.874,0.916,16.445,0.146,8.179,9.834,2.738,0.635,0,0.178,1.719,0.0,0.0,0.0481,Moore_2018_Klyuchevskoy_2,1178.3979,7.847607,1.538746
2,49.172,0.851,15.432,0.157,8.768,10.814,2.544,0.537,0,0.152,2.284,0.0,0.0,0.0590,Moore_2018_Klyuchevskoy_3,1190.2368,7.808848,1.531146
3,49.562,0.935,16.467,0.116,8.610,10.049,2.822,0.632,0,0.174,1.310,0.0,0.0,0.0337,Moore_2018_Klyuchevskoy_4,1187.0610,7.831797,1.535646
4,48.517,0.831,15.055,0.152,9.973,10.987,2.475,0.451,0,0.186,2.095,0.0,0.0,0.0664,Moore_2018_Klyuchevskoy_5,1214.4573,7.798648,1.529146

In [11]:
VESIcal_out=v.BatchFile(filename=None, dataframe=df_HT87, label='Sample_ID')
VESIcal_out.data

,SiO2,TiO2,Al2O3,MnO,MgO,CaO,Na2O,K2O,Cr2O3,P2O5,H2O,NiO,CoO,CO2,Temp,FeO,Fe2O3
Moore_2018_Klyuchevskoy_1,48.347,0.859,19.172,0.128,8.064,9.060,2.748,0.615,0,0.163,1.573,0.0,0.0,0.1528,1176.0864,7.798819,1.529180
Moore_2018_Klyuchevskoy_2,49.874,0.916,16.445,0.146,8.179,9.834,2.738,0.635,0,0.178,1.719,0.0,0.0,0.0481,1178.3979,7.847607,1.538746
Moore_2018_Klyuchevskoy_3,49.172,0.851,15.432,0.157,8.768,10.814,2.544,0.537,0,0.152,2.284,0.0,0.0,0.0590,1190.2368,7.808848,1.531146
Moore_2018_Klyuchevskoy_4,49.562,0.935,16.467,0.116,8.610,10.049,2.822,0.632,0,0.174,1.310,0.0,0.0,0.0337,1187.0610,7.831797,1.535646
Moore_2018_Klyuchevskoy_5,48.517,0.831,15.055,0.152,9.973,10.987,2.475,0.451,0,0.186,2.095,0.0,0.0,0.0664,1214.4573,7.798648,1.529146
Moore_2018_Klyuchevskoy_6,48.401,0.846,15.536,0.141,9.652,11.017,2.576,0.473,0,0.155,1.920,0.0,0.0,0.0601,1208.0052,7.802727,1.529946
Moore_2018_Klyuchevskoy_7,49.806,0.912,16.561,0.132,8.251,9.331,2.847,0.586,0,0.195,2.047,0.0,0.0,0.0541,1179.8451,7.844973,1.538230
Moore_2018_Klyuchevskoy_8,50.513,0.863,15.761,0.159,8.231,9.890,2.889,0.602,0,0.231,1.525,0.0,0.0,0.0132,1179.4431,7.843442,1.537930
Moore_2018_Klyuchevskoy_9,49.825,0.880,16.240,0.186,8.398,10.250,2.751,0.596,0,0.183,1.403,0.0,0.0,0.0381,1182.7998,7.803832,1.530163
Moore_2018_Klyuchevskoy_10,47.054,0.854,14.594,0.140,11.216,12.092,2.387,0.444,0,0.218,1.716,0.0,0.0,0.0562,1239.4416,7.797796,1.528980
Moore_2018_Klyuchevskoy_11,49.342,1.005,17.695,0.103,7.578,10.333,3.015,0.713,0,0.201,0.723,0.0,0.0,0.0308,1166.3178,7.801111,1.529629
Moore_2018_Klyuchevskoy_12,50.631,0.911,15.667,0.147,8.303,9.846,2.660,0.556,0,0.146,1.858,0.0,0.0,0.0525,1180.8903,7.797628,1.528946
Moore_2018_Klyuchevskoy_13,49.808,0.953,17.032,0.141,8.057,10.239,2.961,0.642,0,0.183,0.688,0.0,0.0,0.0205,1175.9457,7.804341,1.530263
Moore_2018_Klyuchevskoy_14,51.494,0.858,15.470,0.220,8.135,9.259,3.074,0.646,0,0.194,1.366,0.0,0.0,0.0054,1177.5135,7.796011,1.528629
Moore_2018_Klyuchevskoy_15,47.812,0.890,16.201,0.148,7.774,12.800,2.772,0.487,0,0.178,1.629,0.0,0.0,0.0721,1170.2574,7.817941,1.532929
Moore_2018_Klyuchevskoy_16,46.786,0.756,14.026,0.136,11.639,12.692,2.177,0.403,0,0.134,1.966,0.0,0.0,0.0766,1247.9439,7.799411,1.529296
Moore_2018_Klyuchevskoy_17,49.212,0.867,16.093,0.196,8.350,10.746,2.527,0.481,0,0.179,2.074,0.0,0.0,0.0862,1181.8350,7.799328,1.529280
Moore_2018_Klyuchevskoy_18,50.125,0.907,16.893,0.191,7.860,10.194,2.897,0.614,0,0.220,0.807,0.0,0.0,0.0236,1171.9860,7.804681,1.530329
Moore_2018_Klyuchevskoy_19,49.514,0.843,14.548,0.141,9.510,10.670,2.750,0.603,0,0.133,2.005,0.0,0.0,0.0532,1205.1510,7.798307,1.529080
Moore_2018_Klyuchevskoy_20,48.455,0.715,14.544,0.148,9.904,12.250,2.268,0.450,0,0.141,1.844,0.0,0.0,0.0746,1213.0704,7.799752,1.529363
Moore_2018_Klyuchevskoy_21,48.823,0.755,15.682,0.170,9.272,11.102,2.367,0.485,0,0.093,1.966,0.0,0.0,0.0520,1200.3672,7.808253,1.531030
Moore_2018_Klyuchevskoy_22,48.020,0.783,15.289,0.187,10.272,11.301,2.506,0.470,0,0.191,1.697,0.0,0.0,0.0496,1220.4672,7.802642,1.529930

In [12]:
df= VESIcal_out.get_data()
chunk_size = 20
subframes = [v.BatchFile(filename=None,dataframe=df.iloc[i:i+chunk_size],label=None) for i in range(0, len(df), chunk_size)]

In [13]:
for index, data in enumerate(subframes):
    if index>=0:
        Sat_P_MagmaSat = data.calculate_saturation_pressure(temperature="Temp")
        filename = f"XH2O_Moore_2018_kluychev_{index}.xlsx"
        Sat_P_MagmaSat.to_excel(excel_writer=filename)

[====================] 100%  Working on sample Moore_2018_Klyuchevskoy_...
[====================] 100%  Working on sample Moore_2018_Klyuchevskoy_...

In [14]:
import os
combined_data = pd.DataFrame()

for index in range(len(subframes)):
    filename = f"XH2O_Moore_2018_kluychev_{index}.xlsx"
    if os.path.exists(filename):
        df = pd.read_excel(filename)
        combined_data = pd.concat([combined_data, df])

combined_filename = "XH2O_Moore_2018_kluychev_combined.xlsx"
combined_data.to_excel(combined_filename, index=False)